# The template used to build iOS project via fastlane
#
# Pre-requirements:
#   - Install fastlane in flow ci agent:
#       https://docs.fastlane.tools/getting-started/ios/setup/
#   
#   - Install CocoaPods in the agent if using pod for library management: 
#       https://guides.cocoapods.org/using/getting-started.html#getting-started
#
#   - Import iOS project required .provisionprofile and .p12 files to agent
#
#   - Setup project name
#     - IOS_PROJECT_NAME: your project name
#
#   - Setup iOS build parameter:
#     - IOS_SCHEME: project scheme name
#     - IOS_EXPORT_METHOD: app-store, ad-hoc, package, enterprise, development, developer-id
#     - IOS_IPA_DIR:
# 
# Import to your project:
#   - Rename ios.flow.yml to .flow.yml and save to project root directory
 
flow:
  - envs:
     IOS_PROJECT_NAME: "flowcidemo"
     IOS_SCHEME: "flowclibasic"
     IOS_EXPORT_METHOD: "development"
     IOS_IPA_DIR: "./ipa_dir"
     
    steps:
      - name: GitClone
        script: |
          rm -r -f ${IOS_PROJECT_NAME}
          git clone ${FLOW_GIT_URL} ${IOS_PROJECT_NAME}

      - name: PodInstall
        script: |
          cd ${IOS_PROJECT_NAME}
          pod install || true
      
      - name: Build
        script: |
          cd ${IOS_PROJECT_NAME}
          fastlane gym --scheme ${IOS_SCHEME} --export_method ${IOS_EXPORT_METHOD} --output_directory ${IOS_IPA_DIR}
      
      - name: GetIPA
        script: |
          cd ${IOS_PROJECT_NAME}
          array=$(find ${IOS_IPA_DIR} -name *.ipa 2>&1)
          for file in ${array[@]}
          do
            echo $file 
          done
