# The template used to build iOS project via fastlane
# Pre-requirements:
#   - Install fastlane in flow ci agent: https://docs.fastlane.tools/getting-started/ios/setup/
#
#   - Import iOS project required .provisionprofile and .p12 files to agent
#
#   - Setup project name
#     - IOS_PROJECT_NAME
#
#   - Setup iOS build parameter:
#     - IOS_SCHEME:
#     - IOS_CONFIGURATION:
#     - IOS_EXPORT_METHOD: app-store, ad-hoc, package, enterprise, development, developer-id
#     - IOS_OUTPUT_DIR:

 
flow:
  - envs:
     IOS_PROJECT_NAME: "flowcidemo"
     IOS_SCHEME: "flowclibasic"
     IOS_EXPORT_METHOD: "development"
     IOS_OUTPUT_DIR: "./ipa_dir"
     
    steps:
      - name: Git Clone
        script: |
          rm -r -f ${IOS_PROJECT_NAME}
          git clone ${FLOW_GIT_URL} ${IOS_PROJECT_NAME}
      
      - name: Build
        script: |
          cd ${IOS_PROJECT_NAME}
          fastlane gym --scheme ${IOS_SCHEME} --export_method ${IOS_EXPORT_METHOD} --output_directory ${IOS_OUTPUT_DIR}
      
      - name: Get IPA
        script: |
          cd ${IOS_PROJECT_NAME}
          array=$(find ${IOS_OUTPUT_DIR} -name *.ipa 2>&1)
          for file in ${array[@]}
          do
            echo $file 
          done
